version: '3.5'
name: 'webmin'
services:
  webmin:
    container_name: webmin_master
    privileged: true
    build:
      context: ./
    volumes:
      - ../docker:/usr/share/webmin/docker:rw
      - ./dind:/home/dind:rw
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "10000:10000"
    cap_add:
      - NET_ADMIN
